cloud-hypervisor/fuse-backend-rs

CODEOWNERS, Cargo.toml, LICENSE-APACHE, LICENSE-BSD-3-Clause, README.md, src/abi/linux_abi.rs, src/abi/mod.rs, src/abi/virtio_fs.rs, src/api/filesystem.rs, src/api/mod.rs, src/api/pseudo_fs.rs, src/api/server.rs, src/api/vfs.rs, src/lib.rs, src/passthrough/fs.rs, src/passthrough/mod.rs, src/passthrough/multikey.rs, src/transport/file_traits.rs, src/transport/fusedev/mod.rs, src/transport/mod.rs, src/transport/virtiofs/fs_cache_req_handler.rs, src/transport/virtiofs/mod.rs
The fuse-backend-rs crate is aimed to provide a pure rust library for
Linux FUSE backends. It reuses source code from the Cloud Hypervisor
and crosvm project, with enhancements and new features as below:
- ABI layer, which defines all data structures shared between linux
Fuse framework and Fuse daemons.
- API layer, defines the interfaces for Fuse daemons to implement a
userspace file system.
- Transport layer, which supports both the Linux Fuse device and
virtio-fs protocol.
- VFS/pseudo_fs, an abstraction layer to support multiple file systems
by a single virtio-fs device.
- A sample passthrough file system implementation, which passes through
files from daemons to clients.
It's co-authored by Liu Bo, Liu Jiang and Peng Tao.
Signed-off-by: Liu Bo <bo.liu@linux.alibaba.com> …
=> Initial implementation of the fuse-backend-rs crate

.gitignore, src/abi/linux_abi.rs, src/api/pseudo_fs.rs, src/api/server.rs, src/api/vfs.rs, src/transport/fusedev/mod.rs
6efbcd4 vfs: fix hash_inode to handle ino being ROOT_ID
3399d86 add gitignore
1e82ef4 correct spelling mistake for split
7188060 fusedev: commit buf from writer when reply error to kernel
d490eeb add umount support for underlying filesystems
4d3e437 fuse: support lookup negative dentry
019cfe6 fusedev: fix account_written for Writer
4b6c4ac vfs: fix vfs mountpoint at root
=> A few bug fixes

Cargo.toml, src/api/vfs.rs, src/passthrough/fs.rs, src/transport/virtiofs/mod.rs
In some situations, we need to close the fds opened by passthorughfs
on fuse server end, and that requires the help of FUSE_FORGET
requests, a typcial use case is that
1) a passthroughfs at /path_to_passthru
2) create a bind mount point at /path_to_passthru/mybind
3) ls /pass_to_passthru/mybind
4) echo 2 > /proc/sys/vm/drop_caches # drop dentry reference on inodes
and send FORGET request
5) umount the bind mnt point.
Now in fuse-rs, forget() method is missing in vfs, and that leads to
step 5) to fail because of EBUSY.
Signed-off-by: Liu Bo <bo.liu@linux.alibaba.com>
=> vfs: add forget support

src/passthrough/fs.rs
Typically passthroughfs's fuse client won't send a FORGET fuse request
for ROOT_ID because ROOT_ID is associated with the fuse mount point on
client end, however that is not the case anymore if passthroughfs is
used as a backend fs because the mount point is not the passthroughfs
itself.
So the end result is that EBADF will be returned when accessing any
files in the passthroughfs if the inode of ROOT_ID is forgotten via
FUSE_FORGET request.
This fixes the issue by filtering ROOT_ID inode.
Signed-off-by: Liu Bo <bo.liu@linux.alibaba.com>
=> passthroughfs: do not forget ROOT_ID

src/api/vfs.rs, src/passthrough/fs.rs
This PR fixes a bug which has been there for a long time way back to crosvm's passthrough version.
It's led to fd leak after readdirplus fuse request is processed, so if the directory accessed by fuse/virtiofs is a mount point, those leaked fds will keep the mount point from being umount.
=> fix fd leak after readdirplus

Cargo.toml
Prepare for publishing v0.1.0 to crates.io.
=> fuse: prepare for publishing v0.1.0 to crates.io

Cargo.toml, README.md, src/api/server/async_io.rs, src/api/server/sync_io.rs, src/async_util.rs, src/passthrough/async_io.rs, src/passthrough/mod.rs, src/transport/fusedev/mod.rs, src/transport/fusedev/session.rs, src/transport/mod.rs, src/transport/virtiofs/mod.rs, tests/example/passthroughfs.rs
Changwei Ge (1):
api: fix fuse init-msg response overflow
Eryu Guan (1):
passthroughfs: don't overwrite existing inode with the same altkey
Liu Jiang (9):
transport/fusedev: refine doc of session manager
transport/fusedev: refine FuseChannel
transport/fusedev: refactor FuseSession interfaces
transport/fusedev: replace epoll with vmm_sys_util::Poll
transport/fusedev: remove several unwrap()
transport: simplify Writer::commit()
async-io: move FuseDevTask to session.rs
transport/fusedev: preallocate buffer for Writer
transport: replace Writer::write_vector()
Peng Tao (3):
clippy: fix unneeded return statements
tests: fix test_new_channel
tests: do not ignore smoke
=> various fixes and improvements

src/abi/linux_abi.rs, src/api/server/async_io.rs, src/api/server/mod.rs, src/api/server/sync_io.rs, src/api/vfs/sync_io.rs, src/passthrough/sync_io.rs
When no_open is enabled, kernel doesn't send open request to fuse
server, so there's no chance for fuse server to handle O_TRUNC open
flag and truncate file to 0. This ends up in non-zero file after a
O_TRUNC open.
Fix it by disabling ATOMIC_O_TRUNC feature when no_open is set, so that
fuse will send setattr request to do the truncate.
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> vfs: disable ATOMIC_O_TRUNC when no_open is set

CHAGNELOG.md, Cargo.toml, src/api/filesystem/async_io.rs, src/api/filesystem/mod.rs, src/api/filesystem/sync_io.rs, src/api/pseudo_fs.rs, src/api/server/async_io.rs, src/api/server/mod.rs, src/api/server/sync_io.rs, src/api/vfs/async_io.rs, src/api/vfs/mod.rs, src/api/vfs/sync_io.rs, src/async_util.rs, src/lib.rs, src/passthrough/async_io.rs, src/passthrough/file_handle.rs, src/passthrough/mod.rs, src/passthrough/multikey.rs, src/passthrough/sync_io.rs, src/transport/file_traits.rs, src/transport/fusedev/mod.rs, src/transport/fusedev/session.rs, src/transport/mod.rs, src/transport/virtiofs/mod.rs, tests/smoke.rs
1. Enhance passthrough to reduce active fds by using file handle
2. Upgrade to latest vm-memory v0.6
3. Enhance fuse-backend crate to support guest dirty page tracking.
=> Enhance passthrough to reduce active fds by using file handle

CHAGNELOG.md, Cargo.toml, src/lib.rs, src/transport/fusedev/mod.rs, src/transport/fusedev/session.rs, src/transport/virtiofs/fs_cache_req_handler.rs
Update dependency to latest version:
1) use vhost from crates.io
2) use vmm-sys-util v0.8
=> Update dependency to latest version

src/api/server/sync_io.rs
To use virtio-fs directories as the upperdir of overlayfs in VMs, we
need to passthrough the RENAME_WHITEOUT flag. The Linux kernel commit
519525fa47b5a8155f0b203e49a3a6a2319f75ae already enabled the passthrough
of the flag. Therefore, let's avoid filtering out it for rename2.
Signed-off-by: Jiachen Zhang <zhangjiachen.jaycee@bytedance.com>
=> server: do not filter out the RENAME_WHITEOUT flag of rename2

Cargo.toml, Makefile, src/api/server/mod.rs, src/lib.rs, src/transport/virtiofs/mod.rs, tests/example/mod.rs, tests/smoke.rs
Bring back virtiofs and vhost-user-fs support so that consumers can use
the latest code to run virtiofs and vhost-user-fs.
=> transport: enable virtiofs and vhost-user-fs

src/api/filesystem/mod.rs
Got:
warning: this attribute can only be applied to a `use` item
--> src/api/filesystem/mod.rs:25:7
|
25 | #[doc(inline)]
|       ^^^^^^ only applicable on `use` items
26 | mod async_io;
| ------------- not a `use` item
|
= note: `#[warn(invalid_doc_attributes)]` on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #82730 <https://github.com/rust-lang/rust/issues/82730>
= note: read https://doc.rust-lang.org/nightly/rustdoc/the-doc-attribute.html#docno_inlinedocinline for more information
This commit would fix this problem.
Signed-off-by: Tim Zhang <tim@hyper.sh>
=> filesystem: fix warnings in rust 1.56

Cargo.toml, src/api/filesystem/mod.rs, src/transport/virtiofs/mod.rs
So that we no longer rely on a non-release git commit.
=> virtiofs: update to use virtio-queue 0.1.0

src/api/filesystem/mod.rs, src/api/filesystem/sync_io.rs, src/api/server/mod.rs, src/api/server/sync_io.rs
Let the underlying file system decide if they want to handle them.
Add ioctl, getlk, setlk, setlkw, bmap and poll support.
Note, for ioctl we return ENOTTY by default to simulate that the API is
actually implemented but no ioctl is supported. This is needed because
newer overlayfs would query underlying fs for some security features and
we cannot return ENOSYS otherwise the error is treated as fatal and
popped up to userspace.
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
=> api: support more server APIs

.github/workflows/rust.yml, Cargo.toml, deny.toml
`advisories` found 3 RUSTSECs on `stderrlog` but there are no known fix to it. `stderrlog` needs to fix itself. These RUSTSECs are safely ignored because we only use `stderrlog` in UT.
=> actions: add cargo deny support

.github/workflows/release.yml, CHAGNELOG.md, Cargo.toml
Add a github action to help publish and release automatically when a new tag is pushed.
Tested here:
https://github.com/bergwolf/fuse-backend-rs/runs/5091078480?check_suite_focus=true
https://github.com/bergwolf/fuse-backend-rs/releases/tag/v1.4.0
https://crates.io/crates/my-test-app-bergwolf/1.4.0
=> release: prepare for the 0.3.0 release

Makefile, tests/smoke.rs
Turns out that we have ignored a few tests by default to make it work
when /dev/fuse is not available. But for docker-smoke, we should really
run them all.
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
=> action: run all tests in docker-smoke

src/api/vfs/mod.rs, src/passthrough/file_handle.rs
* passthroughfs: export file handle and mount fd
* vfs: do not evict pseudofs inodes when unmount
=> sync two minor commits

src/transport/fusedev/linux_session.rs
mio default add EPOLLET to event flags, so epoll will use
edge-triggered mode. It may let poll miss some event, so
manually register the fd with only EPOLLIN flag to
use level-triggered mode.
=> transport: fix get_request in linux

Makefile, src/api/pseudo_fs.rs, src/api/server/async_io.rs, src/passthrough/async_io.rs, src/passthrough/file_handle.rs, src/transport/fusedev/linux_session.rs
Turns out that we missed clippy for a long time by passing a wrong
argument to clippy. Re-enable it and fix all the remaining failures.
=> cargo: fix and enforce clippy

Cargo.toml
This is to fix the warning of `cargo deny check bans`.
Sync to the version of image-service.
```
warning[B004]: found 3 duplicate entries for crate 'nix'
┌─ ./dragonball-sandbox/Cargo.lock:87:1
│
87 │ ╭ nix 0.15.0 registry+https://github.com/rust-lang/crates.io-index
88 │ │ nix 0.22.3 registry+https://github.com/rust-lang/crates.io-index
89 │ │ nix 0.23.1 registry+https://github.com/rust-lang/crates.io-index
│ ╰────────────────────────────────────────────────────────────────^ lock entries
│
= nix v0.15.0
├── dbs-address-space v0.1.0
└── dbs-virtio-devices v0.1.0
= nix v0.22.3
└── fuse-backend-rs v0.4.0
├── blobfs v0.1.0
│   └── dbs-virtio-devices v0.1.0
├── dbs-virtio-devices v0.1.0 (*)
├── nydus-utils v0.1.0
│   ├── rafs v0.1.0
│   │   ├── blobfs v0.1.0 (*)
│   │   └── dbs-virtio-devices …
```
=> upgrade nix to 0.23.1

src/passthrough/async_io.rs, src/passthrough/sync_io.rs
Otherwise we'll get EBADF failure as we can't find handle in handle map.
Fixes: 2895435c15e7 ("passthrough: optimize async_do_getattr/do_getattr()")
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> passthrough: hornor no_open in do_getattr()

Cargo.toml, build.rs, src/transport/fusedev/macos_session.rs, src/transport/fusedev/mod.rs, tests/macfuse_smoke.rs
The diskarbitration-sys crate is out of maintenance, and locks the
core-foundataion-sys crate to an very old version. So avoid dependency
on it.
Signed-off-by: Jiang Liu <gerry@linux.alibaba.com>
=> macos: get rid of dependency on the diskarbitration-sys crate

Cargo.toml, src/api/vfs/async_io.rs, src/common/file_traits.rs, src/passthrough/mod.rs, src/transport/fusedev/macos_session.rs, tests/macfuse_smoke.rs, tests/smoke.rs
Refine Cargo.toml to reduce dependent crates.
root@de1000351b95:/fuse-backend# cargo update
Updating crates.io index
Removing android_system_properties v0.1.4
Removing atty v0.2.14
Removing bumpalo v3.11.0
Updating caps v0.3.4 -> v0.5.4
Removing cc v1.0.73
Removing chrono v0.4.22
Removing errno v0.2.8
Removing errno-dragonfly v0.1.2
Removing error-chain v0.12.4
Removing futures v0.3.23
Removing futures-channel v0.3.23
Removing futures-executor v0.3.23
Removing futures-io v0.3.23
Removing futures-macro v0.3.23
Removing futures-sink v0.3.23
Removing futures-task v0.3.23
Removing futures-util v0.3.23
Removing hermit-abi v0.1.19
Removing iana-time-zone v0.1.46
Removing js-sys v0.3.59
Removing memchr v2.5.0
Removing num-integer v0.1.45
Removing num-traits v0.2.15
Removing num_cpus v1.13.1 …
=> Reduce dependent crates

src/api/vfs/sync_io.rs
Like the commit 345bc0924299ebe9a92210403c10648ba3d5f8e9, we should also
remove ZERO_MESSAGE_OPENDIR when no_opendir is disabled, otherwise,
passthroughfs would always set its no_opendir to true.
Fixes: 345bc0924299ebe9a92210403c10648ba3d5f8e9
Reported-by: Daowen Luo <luodaowen.backend@bytedance.com>
Signed-off-by: Jiachen Zhang <zhangjiachen.jaycee@bytedance.com>
=> Vfs: remove no opendir flags correctly

src/api/server/sync_io.rs
BIG_WRITES doesn't work if FUSE module doesn't support MAX_PAGES.
We should set max_write if BIG_WRITES enabled.
Signed-off-by: henry.hj <henry.hj@antgroup.com>
=> bugfix: fix BIG_WRITES doesn't work

src/passthrough/async_io.rs, src/passthrough/mod.rs, src/passthrough/sync_io.rs
When writeback caching is enabled the kernel is responsible for handling `O_APPEND`. And we only did this in OPEN reuqest but not in CREATE request.
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> passthrough: open file with O_APPEND cleared when writeback is enabled

src/abi/fuse_abi.rs, src/passthrough/sync_io.rs
HEX is more readable for some data, like nodeid/offset/length.
Signed-off-by: gexuyang <gexuyang@linux.alibaba.com>
=> log: print some variables in hexadecimal

src/abi/fuse_abi.rs, src/api/server/sync_io.rs, src/api/vfs/mod.rs, src/common/file_buf.rs, src/lib.rs, src/passthrough/mod.rs, src/transport/fusedev/linux_session.rs, src/transport/fusedev/mod.rs, src/transport/mod.rs
The current upstream flag is defined as:
FUSE_INIT_EXT (1 << 30)
FUSE_HAS_INODE_DAX (1ULL << 33)
We should follow it.
Signed-off-by: Huang Jianan <jnhuang@linux.alibaba.com>
=> abi: fix the conflict of PERFILE_DAX flag

Cargo.toml, src/passthrough/file_handle.rs
Previously, CFileHandle uses a *mut libc::c_char to transfer data between user space and kernel space. The system call "name_to_handle_at" will return the data with "copy_to_user". This may cause a bug because the memory layout of CFileHandle fields may be noncontinuous with the dynamically-sized array's. Therefore, the "copy_to_user" may destroy the stack. This is reproduced on aarch64 only when using "opt-level=3" to compile.
This commit refectors the CFileHandle struct with FarmStruct trait to ensure the memory layout to be continuous. The trait enables struct to own a dynamically-sized array at the end of the struct like zero-array in C language. We refector the related implementation so that "copy_to_user" won't write outside the CFileHandle and destroy the user stack.
Besides, add …
=> bugfix: passthrough: refect CFileHandle struct

Makefile, src/passthrough/mod.rs
Thanks to `cargo clippy` for the suggestion.
See
https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls for background.
Edit: we also need to update our CI's version of Rust, as the necessary feature has only been stabilized recently.
=> Derive Default for CachePolicy (and update Rust CI version)

.github/workflows/rust.yml, src/transport/fusedev/linux_session.rs
Now with fusermount3, we can mount with a normal user. So no need for docker to run somke.
=> workflow: run smoke test w/o docker

src/api/server/sync_io.rs, src/lib.rs
Otherwise, the kernel would fail the reply write syscall with ENOENT and we cannot tell whether it's because fuse connection is closed or not.
=> api: forget and batch forget must not reply

src/api/vfs/sync_io.rs
The filesystem test utility xfs-tests[1] failed on test generic/007 with the error nametest.16 (8370) lookup, should be inumber 72057594037927972. It can be observed in the kernel that the inode number for the file often switches between the hosts inode number and the fuse assigned one.
In the vfs lookup function the out entry inode is set on the top level but does not update attr.st_ino field. Adjust this so that the inode number is correctly set on the attributes.
After this change the test generic/007 passes.
[1] https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/tree/
=> fuse: Ensure lookup sets st_ino of attributes

src/api/server/async_io.rs, src/api/server/sync_io.rs
we found some applications may encounter the io hang:
Call Trace:
[<ffffffff8173ca3b>] ? __schedule+0x23b/0x780
[<ffffffff8173cfb6>] schedule+0x36/0x80
[<ffffffffa0377840>] request_wait_answer+0xc0/0x1f0 [fuse]
[<ffffffff810d5350>] ? prepare_to_wait_event+0x100/0x100
[<ffffffffa03779f4>] __fuse_request_send+0x84/0x90 [fuse]
[<ffffffffa0377a27>] fuse_request_send+0x27/0x30 [fuse]
[<ffffffffa037adaf>] fuse_simple_request+0xcf/0x1a0 [fuse]
[<ffffffffa037c80b>]fuse_dentry_revalidate+0x18b/0x300 [fuse]
[<ffffffff8125b79b>] lookup_fast+0x2eb/0x310
[<ffffffff8125c527>] walk_component+0x47/0x310
[<ffffffff8125d7c7>] path_lookupat+0x67/0x120
[<ffffffff811b6e99>] ? generic_file_read_iter+0x699/0x960
[<ffffffff81260421>] filename_lookup+0xb1/0x180
[<ffffffff812235c6>] ? kmem_cache_alloc+0x146/0x1a0 …
=> fix: low probability IO hang problem

src/api/vfs/async_io.rs, src/api/vfs/mod.rs, src/api/vfs/sync_io.rs
Whenever we convert an entry, make sure the returned attribute st_ino field is updated as well. Otherwise entry.inode and entry.attr.st_ino are not consistent and it might confuse the kernel.
=> api/vfs: ensure entry attr st_ino consistency

src/abi/fuse_abi.rs
It turns out that st.st_nlink is u64 on x86_64 and powerpc64, and u32 on other architectures.
=> abi: st_nlink is u32 on aarch64

src/passthrough/inode_store.rs, src/passthrough/mod.rs, src/passthrough/sync_io.rs
In the current passthroughfs implementation, temporary inodes are allocated and then stored in memory, But a FORGET request causes the inode to be removed from memory, new inodes are reassigned, resulting in the instability of the inodes of a file. this PR implements a stable inode, Limited by the current implementation limitations of VFS, Host inode + mnt + dev needs to be controlled in 56bit, and it is not supported beyond the range.
=> implement stable unique inode for passthroughfs

src/api/filesystem/mod.rs, src/api/server/async_io.rs, src/api/server/mod.rs
Useful for writer of fixed buffer, such FuseDevWriter, VirtioFsWriter
=> feat: ZeroCopyWriter pass through available bytes from inner writer

src/abi/fuse_abi.rs
Add comments to the [`OpenOptions`](https://docs.rs/fuse-backend-rs/0.10.4/fuse_backend_rs/abi/fuse_abi/struct.OpenOptions.html) bitflag struct so that they show up in the generated documentation.
=> abi: properly document OpenOptions flags

Cargo.toml
tokio-uring should compile only if the async-io feature is enabled
=> Avoid compile tokio-uring when use default features

Cargo.toml
The affected dependencies include:
- vmm-sys-util: 0.10 -> 0.11
- vm-memory: 0.9 -> 0.10
- virtio-queue: 0.6 -> 0.7
- vhost: 0.5 -> 0.6
=> deps: Bump versions of dependencies

CHAGNELOG.md, Cargo.toml
3cff242 deps: Bump versions of dependencies
dac955b Avoid compile tokio-uring when use default features
86a46d6 linux_session: support set fusermount binary
f4293a9 fuse: Ensure readdir returns same ino as lookup
9f9b50c api/vfs: implement Display trait for VfsError
d8031bf abi: properly document OpenOptions flags
6d1f933 abi: implement Debug for Entry struct
6e40753 linuxsession: support mount in given mount namespace
ecbd517 cargo: bump version to 0.10.4
e891287 Changelog: prepare to release 0.10.4
c5a44d9 fix: st_nlink in macos aarch64 is u16
2bcc32d feat: ZeroCopyWriter pass through available bytes from inner writer
79d673d CHANGELOG: add more logs for the 0.10.3 release
70dc263 implement stable unique inode for passthroughfs
2d286b2 abi: st_nlink is u32 on aarch64
fb4b1c7 avoid too …
=> release: prepare for v0.10.5 release

.github/workflows/rust.yml, Cargo.toml, Makefile, src/api/server/sync_io.rs, src/transport/fusedev/fuse_t_session.rs, src/transport/fusedev/linux_session.rs, src/transport/fusedev/mod.rs, src/transport/mod.rs, tests/example/macfuse.rs, tests/macfuse_smoke.rs
Use fuse-t to replace MacFUSE as the implementation of FUSE. fuse-t is based on NFS and does not require the use of kernel extensions. Installation can be done with lower privileges and it does not impact system stability.
=> feat: implement fuse-t feature

src/transport/fusedev/macos_session.rs
FuseSession.disk is wrapped by Arc, which is not needed, and this requires DADiskRef to implement Send and Sync.
=> macos_session: remove unneeded Arc

src/transport/fusedev/linux_session.rs
The `allow_other` mount option typically requires root user permissions unless configured otherwise on the machine. It would be nice if this was configurable to allow for unprivileged mounting.
For non-root users to use this option the system must have 'user_allow_other' set in /etc/fuse.conf.
=> linux_session: Make allow_other mount option optional

src/passthrough/mod.rs
Kernel fuse module defaults to KEEP_CACHE in no_open mode, and passthroughfs only sets KEEP_CACHE in cache=always mode. So we should reject no_open if cache is not always.
Also disable writeback cache if cache=none, as we should disable all cache in cache=none mode.
=> passthrough: validate config regarding to cache mode

src/api/pseudo_fs.rs, src/api/server/sync_io.rs, src/api/vfs/mod.rs, src/api/vfs/sync_io.rs, src/lib.rs, src/transport/fusedev/mod.rs
1. In order to make the hot upgrade of virtiofs easy, VFS will save pseudo
inodes when umount for easy recovery. However, in the fuse scenario, if
umount does not remove the pseudo inode, it will cause an invalid
directory to be seen on the host, which is not friendly to users. So add
this option to control this behavior.
2. umount returns the parent's inode information, so that it is convenient
to call fuse's invali entry interface later to clarify the corresponding
dentry cache
3. Use the invalidate entry provided by the fuse kernel to clear the entry
cache, all code references the libfuse implementation.
4. Optimize log output and print in vfs umount scenario
1. optimize the log of forget, for scenarios where forget cannot handle when the vfs submount is dropped by umount.
2. remove …
=> Add the ability to clean up the dentry cache can be used to clean up resources when VFS umount.

src/api/server/async_io.rs, src/api/server/sync_io.rs
clippy doesn't like the solution proposed by rustc. Let's just use the plain if let statement.
error: unused return value of `std::option::Option::<T>::map_or` that must be used
--> src/api/server/sync_io.rs:93:9
|
93 |         hook.map_or((), |h| h.collect(&in_header));
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: if you don't need the returned value, use `if let` instead
= note: `-D unused-must-use` implied by `-D warnings`
=> server: fix cargo build warning

src/api/pseudo_fs.rs, src/api/vfs/mod.rs
In some scenario, we need to access root pseudofs's method in outer caller, so we add a method to export its reference in this patch.
=> vfs: add method to export root pseudofs's reference

src/passthrough/mod.rs, src/passthrough/sync_io.rs
We found when running minio with recent versions of nydus that it was no longer able to boot properly due to Invalid Argument when writing to a temporary file.
Tracing the high-level flow showed that the file was originally opened with O_DIRECT, then later on if the buffer size was not correctly aligned, fcntl with F_SETFL would be used to remove the O_DIRECT flag.
In virtiofs, there is no independent call for fcntl, so the underlying file descriptor opened by nydus still had the O_DIRECT flag set. Meaning that during a write to this file, it would error with -EINVAL as the buffer size was not aligned.
This patch aims to fix this by first recording the open flags for a file in the `HandleData` struct, then on read/write checking these flags match the flags provided by virtiofs in the …
=> fuse: Ensure fd has same flags as read/write

src/transport/fusedev/fuse_t_session.rs, src/transport/fusedev/linux_session.rs, src/transport/fusedev/macos_session.rs, src/transport/fusedev/mod.rs
Refine code syntax, no functional change.
=> transport: refine code syntax, no functional change

src/abi/fuse_abi_linux.rs, src/abi/fuse_abi_macos.rs, src/abi/mod.rs, src/api/server/async_io.rs, src/api/server/sync_io.rs, src/api/vfs/mod.rs, src/api/vfs/sync_io.rs, tests/example/macfuse.rs
MacFUSE is a fork of FUSE version 19 with its own custom flags that sometimes clash with later versions of FUSE. E.g. INIT_EXT flags clashes with MacFUSE flag VOL_RENAME.
So to avoid confussion this change disables all flags and hopefully all functionality not supported on MacOS. This applies both to MacFUSE and FUSE-T because FUSE-T is built to be compatible with MacFUSE and not upstream FUSE.
=> abi: Disable unsupported flags and functionality on MacOS

Cargo.toml, src/api/pseudo_fs.rs, src/api/vfs/mod.rs
This patch add a new sub module `persist` for the `fuse_backend_rs::api::vfs` module.
The `persist` module export two functions to help to save and restore the `Vfs` state:
- `save_to_bytes`, which save the mete data of the `Vfs` struct into a byte array;
- `restore_from_bytes`, which restore the meta data of the `Vfs` struct from a byte array.
As the two above functions only save and restore the vfs meta data, but don't save and restore the backend file systems,
this patch also provides a method named `restore_mount` to re-mount the backend file system into the `Vfs` using the same index as before.
For more information and usage, please refer to the doc of the `save_to_bytes` and `restore_from_bytes` functions.
=> feat: add "persist" feature

src/passthrough/file_handle.rs, src/passthrough/inode_store.rs, src/passthrough/mod.rs, src/passthrough/sync_io.rs, src/passthrough/util.rs
Optimize implementation of lookup() for passthroughfs.
=> Optimize implementation of lookup() for passthroughfs

src/abi/fuse_abi_linux.rs, src/abi/fuse_abi_macos.rs, src/api/filesystem/sync_io.rs, src/api/server/sync_io.rs, src/api/vfs/async_io.rs, src/api/vfs/sync_io.rs, src/passthrough/mod.rs, src/passthrough/sync_io.rs
This patch adds support for fd-passthrough feature (in anolis kernel). The fd-passthrough feature significantly improves the read/write performance of passthrough filesystems.
However, it only supports fuse not virtiofs.
About fd-passthrough, see:
https://gitee.com/anolis/cloud-kernel/commit/ea085d4df6697594772a72b55f1ea53018646c3c https://gitee.com/anolis/cloud-kernel/commit/433ec5ac4cea91cebf5682fa729a570c00bb60c5 https://gitee.com/anolis/cloud-kernel/commit/b4f2155fbfafca7763739b9a5a11585ee59f3c67 https://gitee.com/anolis/cloud-kernel/commit/63c4968a7881f61a2ad04176d3ad3a4e3aa1e706 https://gitee.com/anolis/cloud-kernel/commit/01ec57c17665cd793f115385ac8ba2ca735fe582 https://gitee.com/anolis/cloud-kernel/commit/5c7c7e9ec18fba42d03910ac7501f7e6b472a5f7 …
=> fusedev: add fd-passthrough support

src/passthrough/config.rs, src/passthrough/sync_io.rs
Add support for new cache mode Metadata.
=> ptfs: add support for new cache mode Metadata

src/passthrough/file_handle.rs, src/passthrough/mod.rs, src/passthrough/mount_fd.rs, src/passthrough/sync_io.rs
Use BorrowedFd instead of RawFd when possible.
=> ptfs: use BorrowedFd instead of RawFd when possible

.github/workflows/rust.yml, src/transport/fusedev/linux_session.rs
This patch adds `clone_fuse_file` method to `FuseSession`. 
This function obtains a new file descriptor by opening `/dev/fuse` and associates the file descriptor with the original fuse connection of fuse session using the ioctl `FUSE_DEV_IOC_CLONE` command.
=> fusedev: add `clone_fuse_file` method to `FuseSession`

src/api/server/sync_io.rs
error: cannot process fuse message: Value too large for defined data type
By default, when fuse sever reads the batch forget request, the bufsize given is MAX_BUFFER_SIZE + BUFFER_HEADER_SIZE, and the fuse kernel will fill this buffer as much as possible, so the size of the data that batch forget can fill should be the total buffer size - fuse header - batch forget header
Here's the code for the fuse kernel to fill the batch forget request.
```
struct fuse_batch_forget_in arg = { .count = 0 };
struct fuse_in_header ih = {
.opcode = FUSE_BATCH_FORGET,
.unique = fuse_get_unique(fiq),
.len = sizeof(ih) + sizeof(arg),
};
if (nbytes < ih.len) {
spin_unlock(&fiq->lock);
return -EINVAL;
}
max_forgets = (nbytes - ih.len) / sizeof(struct fuse_forget_one);
head = fuse_dequeue_forget(fiq, …
```
=> Fix batch forget can't handle too large msg

tests/scripts/xfstests_pathr.exclude, tests/scripts/xfstests_pathr.sh
Set xfstests to tag `v2023.12.10` or new test case will break integration CI occasionally.
=> Fix CI: xfstests: restrict xfstests version 

src/transport/fusedev/fuse_t_session.rs
Fixed the issue where the drive icon would appear in the finder when using fuse-t.
=> fix: fuse-t nobrowse

src/passthrough/file_handle.rs, src/passthrough/mod.rs, src/passthrough/sync_io.rs
read/write function invokes
```
self.check_fd_flags(data, f.as_raw_fd(), flags)?;
```
which takes ownership of `data` and it's inner `File`, after the function call returns, File will be dropped and cannot be read/write later anymore, causing a failed read/write.
This bug is triggered when `no_open` config option is set, in this case, `self.get_data` opens a new file and it's dropped immediately after `check_fd_flags`.
The bug can be solved by create a new clone of data by `data.clone()`, the original data(and inner File) can be kept in whole lifetime of read/write function.
=> bugfix: read/write fd dropped unexpectedly.

CHAGNELOG.md, Cargo.toml
Prepare to release v0.12.0 version.
=> release: prepare for v0.12.0 release

src/passthrough/mod.rs
When use_host_ino mode is turned on, we only need to save the by_id relationship if the host inode of the file is larger than MAX_HOST_INO, and don't remove it. however, the previous code used a virtual inode combining the host inode, dev, mnt, and other parts of the file, and this inode is a 56bit inode, which is always larger than MAX_HOST_INO, and so it resulted in the by_id relationship not being cleaned up.
=> fix by_id not free when use_host_ino=true

src/api/server/async_io.rs, src/api/server/sync_io.rs, src/transport/fusedev/linux_session.rs
The fuse directio call path is as follows
```
fuse_read_fill+0xa8/0xb0
fuse_send_read+0x3f/0xb0
fuse_direct_io+0x34a/0x5f0
__fuse_direct_read+0x4e/0x70
fuse_file_read_iter+0x9e/0x140
new_sync_read+0xde/0x120
__vfs_read+0x27/0x40
vfs_read+0x94/0x190
ksys_read+0x4e/0xd0
```
under the direct io path, fuse initiates a request whose request size is determined by the combination of the user-supplied buffer size and max_read mount parameters.
```
size_t nmax = write ? fc->max_write : fc->max_read; 
size_t count = iov_iter_count(iter);
size_t nbytes = min(count, nmax);
nres = fuse_send_read(req, io, pos, nbytes, owner);
```
so we have a problem with the checking of the request size in the code, we always compare the request size with MAX_BUFFER_SIZE, but in fact the maximum value of the request …
=> fix request size too large when use direct io

src/passthrough/config.rs, src/passthrough/sync_io.rs
Filter out the libc::O_DIRECT flag at open_inode. Also, add the "allow_direct_io" flag to allow users to make the file system to honor the flag instead.
reference virtiofsd 894361d1e83c23460ce9aaadc40a6af598a790d4
=> Filter out O_DIRECT at open_inode

.github/workflows/rust.yml, Makefile, src/api/server/mod.rs, src/api/server/sync_io.rs, src/passthrough/sync_io.rs
Port some unit test code to upstream.
Thanks to the original author: Xiao Jietao (六滔)
=> Add unit tests for passthroughfs and fuser server api

.github/workflows/rust.yml, Cargo.toml, deny.toml, src/abi/fuse_abi_linux.rs, src/abi/fuse_abi_macos.rs, src/api/filesystem/mod.rs, src/api/filesystem/overlay.rs, src/api/server/mod.rs, src/api/server/sync_io.rs, src/common/file_buf.rs, src/lib.rs, src/overlayfs/mod.rs, src/passthrough/config.rs, src/passthrough/file_handle.rs, src/passthrough/sync_io.rs, src/transport/fs_cache_req_handler.rs, src/transport/fusedev/fuse_t_session.rs, src/transport/fusedev/macos_session.rs, src/transport/fusedev/mod.rs, src/transport/mod.rs, src/transport/virtiofs/mod.rs
To fix this https://github.com/dragonflyoss/nydus/issues/1647, we need bump `vm-memory` and `vmm-sys-util` here first. The releated RUSTSEC advisories are [RUSTSEC-2023-0056](https://rustsec.org/advisories/RUSTSEC-2023-0056) and [RUSTSEC-2024-0002](https://rustsec.org/advisories/RUSTSEC-2024-0002).
In addtion, since the `async_io` is not a supported feature as #188 mentioned, I removed the related code in linux_session.rs to address the clippy error in CI. Now all [CI](https://github.com/BraveY/fuse-backend-rs/actions/runs/12908477335) got green. @PlamenHristov cc.
=> Bump dependencies version to resolve the RUSTSEC warnning.

.github/workflows/rust.yml, Cargo.toml
To fix the [broken CI](https://github.com/cloud-hypervisor/fuse-backend-rs/actions/runs/13238505121)  caused by a version bump in virtio-bindings, we need to pin the version to v0.2.4.
=> chore: fix broken CI by pinning virtio-bindings to v0.2.4

src/api/filesystem/overlay.rs, src/api/vfs/sync_io.rs, src/passthrough/sync_io.rs, src/passthrough/util.rs, src/transport/fusedev/mod.rs
when no_open=false, no_opendir=true, we can't execute the sync command on the directory, because fsyncdir uses get_data to get the handle of the directory, but no_open=false, so it will go to the handle map to find it, but in fact this is a directory, and the no_opendir is true, so it is not in the handle map, It needs to be reopened.
#204
=> Fix: unable to perform sync on directory

src/api/server/sync_io.rs, src/api/vfs/mod.rs, src/passthrough/mod.rs
This PR includes two related improvements to better support multi-filesystem
mounting scenarios on fuse, especially during unmount operations:
1. Add `notify_inval_inode` support in fusedev, enabling user space to
explicitly notify the kernel to invalidate inode page caches. This helps
clear caches properly after unmounting.
2. Extend the VFS method `get_rootfs` to return both the mounted backend
filesystem (Arc<BackFileSystem>) and its associated filesystem index
(fs_idx). Although multi-filesystem mounting is already supported,
returning fs_idx is necessary for proper unmount handling and cache
invalidation.
The implementation follows fuse kernel and libfuse protocols and maintains
compatibility with existing patterns like notify_inval_entry.
=> Add notify_inval_inode and extend get_rootfs to return fs_idx for umount

src/api/server/sync_io.rs
This PR fixes the len of OutHeader when notifying kernel to resend fuse requests. The original code can cause an EINVAL error.
=> Fix fuse out header len in notify_resend

src/transport/fusedev/linux_session.rs, src/transport/fusedev/macos_session.rs, src/transport/fusedev/mod.rs, src/transport/mod.rs, tests/passthrough/src/main.rs
`with_writer` docs
- Introduce `try_with_writer<F, R, E>` that builds a `FuseDevWriter` and returns
the closure’s `Result`, converting `super::Error` via `From`.
- Return `SessionFailure("invalid fuse session")` when `self.file` is absent.
- Tweak `with_writer` doc to clarify it passes a writer to the given closure.
example(passthrough): update example to show how to use try_with_writer
=> feat(fusedev): add `try_with_writer` on `FuseSession`; update
