cloud-hypervisor/fuse-backend-rs

.github/workflows/rust.yml
Cargo.toml
src/transport/virtiofs/mod.rs

This fixes fuse-backend-rs to pass build by using the correct vm-virtio crate.
Also a CI action file is added.

build fix and CI support 

---

.github/workflows/rust.yml
src/api/server.rs
src/api/vfs.rs
src/lib.rs
src/passthrough/fs.rs
src/transport/fusedev/mod.rs
src/transport/virtiofs/mod.rs

1. server: try best efforts to convert error kind to os error 
2. fuse-rs: provide get_root_fs to find backend fs by mount point
3. virtiofs: fix clippy warnning
4. enable clippy and fotmat checks in CI

A few improvements

---

src/passthrough/fs.rs

We need to make sure fd is closed in all cases. Right now it is
not closed in create() when no_open is enabled.
Add a helper to fold all openat() calls and always return a File
struct so that fd is always closed when File goes out of scope.
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
Signed-off-by: Liu Bo <bo.liu@linux.alibaba.com>

passthru: fix fd leak in create

---

src/api/server.rs
src/api/vfs.rs
src/lib.rs
src/passthrough/fs.rs
src/transport/fusedev/mod.rs
src/transport/mod.rs

This series includes several bugfixes for fusedev/passthrough

Several bugfixes for fusedev/passthrough

---

Cargo.toml
src/abi/virtio_fs.rs
src/api/filesystem.rs
src/api/server.rs
src/lib.rs
src/transport/file_traits.rs
src/transport/fusedev/mod.rs
src/transport/mod.rs
src/transport/virtiofs/fs_cache_req_handler.rs
src/transport/virtiofs/mod.rs

1) improve documentation
2) add more unit tests
3) fix several minor bugs
4) minor performance optimization

Improve documentation and minor bugfix

---

src/api/vfs.rs
src/passthrough/fs.rs

Eryu Guan (1):
passthroughfs: make xattr ops work with symlink
Peng Tao (4):
vfs: init backend fs properly
passthroughfs: add no_opendir support
passthroughfs: fix readlink buffer size
vfs: downgrade get_rootfs failure log level

fix a couple of issues

---

.github/workflows/rust.yml
Cargo.toml
src/lib.rs

Prepare for publishing v0.1.0 to crates.io.

fuse: prepare for publishing v0.1.0

---

.github/workflows/rust.yml
README.md
tests/example/passthroughfs.rs

refine README.md with usage examples

---

CHAGNELOG.md
Cargo.toml

set readme file for the crate

---

README.md

refine README.md to reference more examples

---

Cargo.toml

prepare for releasing v0.1.1

---

README.md

refine README.md

---

.github/workflows/rust.yml
Makefile

So that we indeed run a live fuse daemon to test.

actions: run smoke test in docker

---

Cargo.toml
src/abi/linux_abi.rs
src/api/filesystem/async_io.rs
src/api/filesystem/mod.rs
src/api/filesystem/sync_io.rs
src/api/mod.rs
src/api/server/async_io.rs
src/api/server/sync_io.rs
src/api/vfs/async_io.rs
src/api/vfs/mod.rs
src/api/vfs/sync_io.rs
src/passthrough/async_io.rs
src/passthrough/mod.rs
src/passthrough/sync_io.rs

1) enhance the Server to support KILLPRIV_v2
2) enhance vfs to support setup_mapping for DAX.

Support killpriv_v2 and DAX window

---

Cargo.toml

Release v0.1.2

---

CHAGNELOG.md
CODEOWNERS
Cargo.toml
src/api/filesystem/async_io.rs
src/api/filesystem/mod.rs
src/api/filesystem/sync_io.rs
src/api/mod.rs
src/api/pseudo_fs.rs
src/api/server/async_io.rs
src/api/server/mod.rs
src/api/server/sync_io.rs
src/api/vfs/async_io.rs
src/api/vfs/mod.rs
src/api/vfs/sync_io.rs
src/passthrough/async_io.rs
src/passthrough/file_handle.rs
src/passthrough/mod.rs
src/passthrough/sync_io.rs
src/transport/file_traits.rs
src/transport/file_volatile_slice.rs
src/transport/fusedev/mod.rs
src/transport/fusedev/session.rs
src/transport/mod.rs
src/transport/virtiofs/mod.rs

- add more checks on path names passed from fuse kernel module
- some minor bug fixes
- update vm-memory to 0.7.0
- add @eryugey to CODEOWNERS
- bump version to 0.2.0

prepare for 0.2.0 release

---

.github/workflows/rust.yml
Makefile
src/api/server/sync_io.rs
src/passthrough/mod.rs
src/transport/fusedev/linux_session.rs
src/transport/fusedev/macos_session.rs
src/transport/fusedev/mod.rs
tests/example/macfuse.rs
tests/example/passthroughfs.rs
tests/macfuse_smoke.rs

Clippy fix

---

src/transport/fusedev/macos_session.rs

transport: fix mac_session wake api signature

---

src/api/server/sync_io.rs

macfuse kernel need the reply to exit.

api: reply destory ok

---

src/transport/virtiofs/mod.rs

In dragonball-sandbox's virtiofs device, when using Reader/Writer,
the specific type of GuestMemory is not known, so generic parameters
are needed here.
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>

virtiofs: Modify the `new` interface of Reader/Writer.

---

src/transport/fusedev/linux_session.rs

Otherwise, we might end up missing the EXIT_FUSE_EVENT event because
the function returns when handling the FUSE_DEV_EVENT event.

fusedev: handle all events before returning

---

src/transport/fusedev/linux_session.rs
src/transport/fusedev/macos_session.rs

1. Fixed an issue where epoll exited because EINTR was not processed
2. Fix the issue that EAGIN handled incorrectly
ref: https://github.com/libfuse/libfuse/blob/master/lib/fuse_lowlevel.c#L2807
ref: https://github.com/google/crosvm/blob/4c0de58cbf94291568906a479e91ed075bd91470/base/src/sys/unix/poll.rs#L214
Signed-off-by: zyfjeff <zyfjeff@linux.alibaba.com>

fusedev: Fixed some issues about EINTR and EAGIN handled incorrectly

---

CHAGNELOG.md
src/transport/file_volatile_slice.rs

Implement Sync for FileVolatileSlice to support rust async fn.

Implement Sync for FileVolatileSlice

---

CHAGNELOG.md
Cargo.toml

Prepare for releasing v0.9.2

---

Cargo.toml

solve the issue: https://github.com/openanolis/dragonball-sandbox/issues/166
Signed-off-by: uran0sH <huangwenyuu@outlook.com>

upgrade vm-memory to 0.8.0

---

Cargo.toml
deny.toml
src/api/pseudo_fs.rs
src/transport/fusedev/linux_session.rs

Update dependency to latest versions

Update dependency to latest versions

---

CHAGNELOG.md
Cargo.toml

Prepare for releasing v0.9.5.
Signed-off-by: Jiang Liu <gerry@linux.alibaba.com>

Prepare for releasing v0.9.5

---

src/passthrough/async_io.rs
src/passthrough/mod.rs
src/passthrough/sync_io.rs

When writeback caching is enabled, the kernel may send read requests
even if the userspace program opened the file write-only. So we need to
ensure that we have opened the file for reading as well as writing.
But we only did this when handling OPEN request, CREATE request with
O_WRONLY still misses read permission. This results in EBADF error when
writing such file from client side.
Fix it by introducing get_writeback_open_flags() function, which ensures
read permission is granted, and call this helper function in both open
and create code path.
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>

passthrough: open file for reading if writeback cache is enabled

---

src/api/vfs/sync_io.rs

At present, the entry.inode is the correct inode number, but the linux kernel uses the entry.attr.st_ino as inode number. So, we should correct the value of entry.attr.st_ino to let it work.
This PR is related to https://github.com/dragonflyoss/image-service/issues/851
Result:
Signed-off-by: Bin Tang <tangbin.bin@bytedance.com>

vfs: fix incorrect st_ino in entry.attr

---

src/api/vfs/mod.rs

Correctly set attr.st_ino for loopup(), otherwise stat() syscall may get wrong data.
Signed-off-by: Jiang Liu <gerry@linux.alibaba.com>

vfs: correctly set attr.st_ino for loopup()

---

CHAGNELOG.md
Cargo.toml

Prepare for releasing v0.10.1.
Signed-off-by: Jiang Liu <gerry@linux.alibaba.com>

Prepare for releasing v0.10.1

---

tests/smoke.rs

Fix a failure related to git in smoke tests.

test: fix a failure related to git in smoke tests

---

src/transport/fusedev/linux_session.rs

Use libfuses's fusermount3 to mount as regular user without requiring root.
With many thanks to @fzgregor Franz Gregor for the initial prototype.
The patch uses the same strategy as libfuse: first we try to mount via kernel syscalls, and if that fails, we fall back to using the fusermount binary.
Fixes https://github.com/cloud-hypervisor/fuse-backend-rs/issues/76

Support non-privileged users

---

src/transport/fusedev/linux_session.rs

So we could mount fuse in another mount namespace.

linuxsession: support mount in given mount namespace

---

src/api/filesystem/mod.rs

Add an extra derive to the Entry struct.

abi: implement Debug for Entry struct

---

src/api/vfs/mod.rs

api/vfs: implement Display trait for VfsError

---

src/transport/fusedev/linux_session.rs

Use fusermount3 by default, and could set binary path to fusermount if needed.

linux_session: support set fusermount binary

---

src/api/server/sync_io.rs
src/api/vfs/mod.rs

Clean up code related to macos.
Follow up of https://github.com/cloud-hypervisor/fuse-backend-rs/pull/162

macos: clean up code related to macos

---

Cargo.toml
Makefile
src/api/server/async_io.rs
src/api/server/sync_io.rs
src/api/vfs/mod.rs
src/api/vfs/sync_io.rs

Fix a build failure related to conditional compilation: error[E0063]: missing field `id_mapping` in initializer of `VfsOptions`
--> src/api/vfs/mod.rs:751:16
|
751 |             Ok(VfsOptions {
|                ^^^^^^^^^^ missing `id_mapping`

build: fix a build failure related to conditional compilation

---

.github/workflows/xfstests.yml
.gitignore
tests/passthrough/Cargo.toml
tests/passthrough/src/main.rs
tests/scripts/xfstests_pathr.exclude
tests/scripts/xfstests_pathr.sh

Involve new github Action to run xfstests for passthrough fs.

CI: add xfstests for passthrough fs

---

.github/workflows/rust.yml
.github/workflows/xfstests.yml
Makefile
src/abi/fuse_abi_linux.rs

And enable multi-arch build/check actions.

abi: unify st_nlink

---

src/passthrough/mod.rs

Refine implementation of seal_size_check() with better handling of fallocate flags.

ptfs: refine implementation of seal_size_check()
